### ISSUE TITLE
Missing API Key Information for Holyheld SDK Usage

### ISSUE THREAD

**Issue by QuenumGerald** [holyheld/hh-v1-sdk#11]
Hi,

I am currently working on integrating the Holyheld SDK and have come across an issue. The documentation mentions that a HOLYHELD_SDK_API_KEY is required to use the SDK and that it can be obtained by reaching out to a Holyheld point of contact.

However, I cannot find any clear instructions or contact details regarding where or how to obtain this API key. Could you provide guidance on the process to obtain the HOLYHELD_SDK_API_KEY or update the documentation with this information?

Any help would be appreciated.

Thanks!

**Comment by amozgov** [comment]
Hey QuenumGerald! Thank you for reaching out. Happy to help here, if you can please reach out to hello@holyheld.com our team would love to learn more about what you are building 🙌

**Comment by QuenumGerald** [comment]
Sure ! Thanks 👍🏿
